# Generated by Django 3.0.8 on 2020-08-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=20)),
                ('Product_category', models.CharField(max_length=25)),
                ('Product_subcategory', models.CharField(max_length=25)),
                ('Product_description', models.CharField(max_length=500)),
                ('Product_price', models.IntegerField(default='0')),
                ('Product_PubDate', models.DateField(default='')),
                ('Product_image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
