# Generated by Django 3.0.8 on 2020-07-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=16)),
                ('Address', models.CharField(max_length=50)),
                ('Address2', models.CharField(default='', max_length=50)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=25)),
                ('zip', models.CharField(max_length=15)),
            ],
        ),
    ]
